import { CancellationToken } from './cancellation-token';
import { StreamQueue } from './stream-queue';
import { SessionStateMachine } from './session-state';

// @ts-ignore
import WebSocket from 'ws';

export class PlaybackController {
  private queue: StreamQueue;
  private cancelToken: CancellationToken | null = null;
  private isPlaying: boolean = false;
  private isStreamActive: boolean = false;
  private completionResolver: (() => void) | null = null;

  constructor() {
    this.queue = new StreamQueue();
  }

  public getQueue(): StreamQueue {
    return this.queue;
  }
  
  public setStreamActive(active: boolean) {
    this.isStreamActive = active;
  }
  
  public async waitForCompletion(): Promise<void> {
    if (!this.isPlaying && !this.isStreamActive) return Promise.resolve();
    return new Promise(resolve => {
      this.completionResolver = resolve;
    });
  }

  public async startPlayback(ws: WebSocket, streamSid: string, token: CancellationToken, stateMachine: SessionStateMachine): Promise<void> {
    if (this.isPlaying) return;
    this.isPlaying = true;
    this.cancelToken = token;

    const CHUNK_SIZE = 160;
    const INTERVAL_MS = 20;

    return new Promise((resolve) => {
      const _resolve = () => {
        if (this.completionResolver) {
          this.completionResolver();
          this.completionResolver = null;
        }
        resolve();
      };
      
      const interval = setInterval(() => {
        if (this.cancelToken?.isCancelled) {
          clearInterval(interval);
          this.queue.flush();
          this.isPlaying = false;
          this.isStreamActive = false;
          
          if (ws.readyState === WebSocket.OPEN) {
            // Immediate handset buffer flush
            ws.send(JSON.stringify({
              event: 'clear',
              streamSid
            }));
            console.log('[INTERRUPT] Twilio handset clear signal sent.');
          }
          _resolve();
          return;
        }

        if (ws.readyState !== WebSocket.OPEN) {
          clearInterval(interval);
          this.queue.flush();
          this.isPlaying = false;
          this.isStreamActive = false;
          _resolve();
          return;
        }

        // We pull exactly CHUNK_SIZE from the queue for precise 20ms timing
        // But StreamQueue currently dequeues Buffer elements directly (which are already chunked properly from Piper)
        const nextChunk = this.queue.dequeue();
        
        if (nextChunk) {
          // Play chunk
          // In the future, slice nextChunk to exact CHUNK_SIZE if Piper chunks are irregular, but mulaw chunks generated by our code are 160 bytes anyway
          let offset = 0;
          while (offset < nextChunk.length) {
            const chunk = nextChunk.subarray(offset, offset + CHUNK_SIZE);
            offset += CHUNK_SIZE;
            const payload = chunk.toString('base64');
            ws.send(JSON.stringify({
              event: 'media',
              streamSid,
              media: { payload }
            }));
          }
        } else {
          // If queue is empty, check if stream is still active
          if (!this.isStreamActive) {
            clearInterval(interval);
            this.isPlaying = false;
            console.log('[PLAYBACK] Queue drained — remaining in LISTENING');
            _resolve();
          }
        }
      }, INTERVAL_MS);
    });
  }

  public abort(): void {
    if (this.cancelToken) {
      this.cancelToken.cancel();
    }
  }
}
